//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcitas.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContratoPrestamo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContratoPrestamo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appcitas.Recursos.ContratoPrestamo", typeof(ContratoPrestamo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 257.
        /// </summary>
        internal static string Anio_X {
            get {
                return ResourceManager.GetString("Anio_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 870.
        /// </summary>
        internal static string Anio_Y {
            get {
                return ResourceManager.GetString("Anio_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 255.
        /// </summary>
        internal static string Descripcion_X {
            get {
                return ResourceManager.GetString("Descripcion_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 472.
        /// </summary>
        internal static string Descripcion_Y {
            get {
                return ResourceManager.GetString("Descripcion_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 536.
        /// </summary>
        internal static string Dia_X {
            get {
                return ResourceManager.GetString("Dia_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 857.
        /// </summary>
        internal static string Dia_Y {
            get {
                return ResourceManager.GetString("Dia_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 175.
        /// </summary>
        internal static string Direccion_X {
            get {
                return ResourceManager.GetString("Direccion_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 252.
        /// </summary>
        internal static string Direccion_Y {
            get {
                return ResourceManager.GetString("Direccion_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 267.
        /// </summary>
        internal static string GarantiaDescripcion_X {
            get {
                return ResourceManager.GetString("GarantiaDescripcion_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 495.
        /// </summary>
        internal static string GarantiaDescripcion_Y {
            get {
                return ResourceManager.GetString("GarantiaDescripcion_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 400.
        /// </summary>
        internal static string Identidad_X {
            get {
                return ResourceManager.GetString("Identidad_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 238.
        /// </summary>
        internal static string Identidad_Y {
            get {
                return ResourceManager.GetString("Identidad_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 465.
        /// </summary>
        internal static string IdentidadFirma_X {
            get {
                return ResourceManager.GetString("IdentidadFirma_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 973.
        /// </summary>
        internal static string IdentidadFirma_Y {
            get {
                return ResourceManager.GetString("IdentidadFirma_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 383.
        /// </summary>
        internal static string IdPrestamo_X {
            get {
                return ResourceManager.GetString("IdPrestamo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 150.
        /// </summary>
        internal static string IdPrestamo_Y {
            get {
                return ResourceManager.GetString("IdPrestamo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 145.
        /// </summary>
        internal static string Mes_X {
            get {
                return ResourceManager.GetString("Mes_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 870.
        /// </summary>
        internal static string Mes_Y {
            get {
                return ResourceManager.GetString("Mes_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 264.
        /// </summary>
        internal static string Monto_X {
            get {
                return ResourceManager.GetString("Monto_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 325.
        /// </summary>
        internal static string Monto_Y {
            get {
                return ResourceManager.GetString("Monto_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 387.
        /// </summary>
        internal static string Nombre_X {
            get {
                return ResourceManager.GetString("Nombre_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 224.
        /// </summary>
        internal static string Nombre_Y {
            get {
                return ResourceManager.GetString("Nombre_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 465.
        /// </summary>
        internal static string NombreFirma_X {
            get {
                return ResourceManager.GetString("NombreFirma_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 960.
        /// </summary>
        internal static string NombreFirma_Y {
            get {
                return ResourceManager.GetString("NombreFirma_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 235.
        /// </summary>
        internal static string NumeroCuotas_X {
            get {
                return ResourceManager.GetString("NumeroCuotas_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 375.
        /// </summary>
        internal static string NumeroCuotas_Y {
            get {
                return ResourceManager.GetString("NumeroCuotas_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 235.
        /// </summary>
        internal static string Plazo_X {
            get {
                return ResourceManager.GetString("Plazo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 349.
        /// </summary>
        internal static string Plazo_Y {
            get {
                return ResourceManager.GetString("Plazo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 232.
        /// </summary>
        internal static string PorcentajeInteres_X {
            get {
                return ResourceManager.GetString("PorcentajeInteres_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 448.
        /// </summary>
        internal static string PorcentajeInteres_Y {
            get {
                return ResourceManager.GetString("PorcentajeInteres_Y", resourceCulture);
            }
        }
    }
}
