//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcitas.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReciboOtros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReciboOtros() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appcitas.Recursos.ReciboOtros", typeof(ReciboOtros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 169.
        /// </summary>
        internal static string Clave_X {
            get {
                return ResourceManager.GetString("Clave_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 271.
        /// </summary>
        internal static string Clave_Y {
            get {
                return ResourceManager.GetString("Clave_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 177.
        /// </summary>
        internal static string Concepto_X {
            get {
                return ResourceManager.GetString("Concepto_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 286.
        /// </summary>
        internal static string Concepto_Y {
            get {
                return ResourceManager.GetString("Concepto_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 170.
        /// </summary>
        internal static string Fecha_X {
            get {
                return ResourceManager.GetString("Fecha_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 256.
        /// </summary>
        internal static string Fecha_Y {
            get {
                return ResourceManager.GetString("Fecha_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 177.
        /// </summary>
        internal static string Nombre_X {
            get {
                return ResourceManager.GetString("Nombre_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 241.
        /// </summary>
        internal static string Nombre_Y {
            get {
                return ResourceManager.GetString("Nombre_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 156.
        /// </summary>
        internal static string NoRecibo_X {
            get {
                return ResourceManager.GetString("NoRecibo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 226.
        /// </summary>
        internal static string NoRecibo_Y {
            get {
                return ResourceManager.GetString("NoRecibo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 202.
        /// </summary>
        internal static string TotalRecibo_X {
            get {
                return ResourceManager.GetString("TotalRecibo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 301.
        /// </summary>
        internal static string TotalRecibo_Y {
            get {
                return ResourceManager.GetString("TotalRecibo_Y", resourceCulture);
            }
        }
    }
}
