//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcitas.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReciboPagoPrestamos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReciboPagoPrestamos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appcitas.Recursos.ReciboPagoPrestamos", typeof(ReciboPagoPrestamos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 165.
        /// </summary>
        internal static string Documento_X {
            get {
                return ResourceManager.GetString("Documento_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 256.
        /// </summary>
        internal static string Documento_Y {
            get {
                return ResourceManager.GetString("Documento_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 180.
        /// </summary>
        internal static string Fecha_X {
            get {
                return ResourceManager.GetString("Fecha_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 271.
        /// </summary>
        internal static string Fecha_Y {
            get {
                return ResourceManager.GetString("Fecha_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 182.
        /// </summary>
        internal static string Nombre_X {
            get {
                return ResourceManager.GetString("Nombre_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 241.
        /// </summary>
        internal static string Nombre_Y {
            get {
                return ResourceManager.GetString("Nombre_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 165.
        /// </summary>
        internal static string NoRecibo_X {
            get {
                return ResourceManager.GetString("NoRecibo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 226.
        /// </summary>
        internal static string NoRecibo_Y {
            get {
                return ResourceManager.GetString("NoRecibo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 208.
        /// </summary>
        internal static string ReciboTotal_X {
            get {
                return ResourceManager.GetString("ReciboTotal_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 314.
        /// </summary>
        internal static string ReciboTotal_Y {
            get {
                return ResourceManager.GetString("ReciboTotal_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 208.
        /// </summary>
        internal static string Saldo_X {
            get {
                return ResourceManager.GetString("Saldo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 299.
        /// </summary>
        internal static string Saldo_Y {
            get {
                return ResourceManager.GetString("Saldo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 179.
        /// </summary>
        internal static string Tipo_X {
            get {
                return ResourceManager.GetString("Tipo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 286.
        /// </summary>
        internal static string Tipo_Y {
            get {
                return ResourceManager.GetString("Tipo_Y", resourceCulture);
            }
        }
    }
}
