//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcitas.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReporteArqueo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReporteArqueo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appcitas.Recursos.ReporteArqueo", typeof(ReporteArqueo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string B1_X {
            get {
                return ResourceManager.GetString("B1_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 297.
        /// </summary>
        internal static string B1_Y {
            get {
                return ResourceManager.GetString("B1_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string B10_X {
            get {
                return ResourceManager.GetString("B10_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 345.
        /// </summary>
        internal static string B10_Y {
            get {
                return ResourceManager.GetString("B10_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string B100_X {
            get {
                return ResourceManager.GetString("B100_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 391.
        /// </summary>
        internal static string B100_Y {
            get {
                return ResourceManager.GetString("B100_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string B2_X {
            get {
                return ResourceManager.GetString("B2_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 313.
        /// </summary>
        internal static string B2_Y {
            get {
                return ResourceManager.GetString("B2_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string B20_X {
            get {
                return ResourceManager.GetString("B20_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 359.
        /// </summary>
        internal static string B20_Y {
            get {
                return ResourceManager.GetString("B20_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string B5_X {
            get {
                return ResourceManager.GetString("B5_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 329.
        /// </summary>
        internal static string B5_Y {
            get {
                return ResourceManager.GetString("B5_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string B50_X {
            get {
                return ResourceManager.GetString("B50_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 375.
        /// </summary>
        internal static string B50_Y {
            get {
                return ResourceManager.GetString("B50_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string B500_X {
            get {
                return ResourceManager.GetString("B500_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 406.
        /// </summary>
        internal static string B500_Y {
            get {
                return ResourceManager.GetString("B500_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string EntregadoEfectivo_X {
            get {
                return ResourceManager.GetString("EntregadoEfectivo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 173.
        /// </summary>
        internal static string EntregadoEfectivo_Y {
            get {
                return ResourceManager.GetString("EntregadoEfectivo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string EntregadoTesorero_X {
            get {
                return ResourceManager.GetString("EntregadoTesorero_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 204.
        /// </summary>
        internal static string EntregadoTesorero_Y {
            get {
                return ResourceManager.GetString("EntregadoTesorero_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 480.
        /// </summary>
        internal static string EstadoCajero_X {
            get {
                return ResourceManager.GetString("EstadoCajero_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 96.
        /// </summary>
        internal static string EstadoCajero_Y {
            get {
                return ResourceManager.GetString("EstadoCajero_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string Faltante_X {
            get {
                return ResourceManager.GetString("Faltante_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 590.
        /// </summary>
        internal static string Faltante_Y {
            get {
                return ResourceManager.GetString("Faltante_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 327.
        /// </summary>
        internal static string Fecha_X {
            get {
                return ResourceManager.GetString("Fecha_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 96.
        /// </summary>
        internal static string Fecha_Y {
            get {
                return ResourceManager.GetString("Fecha_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string InicioDia_X {
            get {
                return ResourceManager.GetString("InicioDia_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 143.
        /// </summary>
        internal static string InicioDia_Y {
            get {
                return ResourceManager.GetString("InicioDia_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string M1_X {
            get {
                return ResourceManager.GetString("M1_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 453.
        /// </summary>
        internal static string M1_Y {
            get {
                return ResourceManager.GetString("M1_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string M10_X {
            get {
                return ResourceManager.GetString("M10_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string M10_Y {
            get {
                return ResourceManager.GetString("M10_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string M2_X {
            get {
                return ResourceManager.GetString("M2_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 469.
        /// </summary>
        internal static string M2_Y {
            get {
                return ResourceManager.GetString("M2_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string M20_X {
            get {
                return ResourceManager.GetString("M20_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 515.
        /// </summary>
        internal static string M20_Y {
            get {
                return ResourceManager.GetString("M20_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string M5_X {
            get {
                return ResourceManager.GetString("M5_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 484.
        /// </summary>
        internal static string M5_Y {
            get {
                return ResourceManager.GetString("M5_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string M50_X {
            get {
                return ResourceManager.GetString("M50_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 530.
        /// </summary>
        internal static string M50_Y {
            get {
                return ResourceManager.GetString("M50_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 152.
        /// </summary>
        internal static string NombreCajero_X {
            get {
                return ResourceManager.GetString("NombreCajero_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 96.
        /// </summary>
        internal static string NombreCajero_Y {
            get {
                return ResourceManager.GetString("NombreCajero_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string RecibidoEfectivo_X {
            get {
                return ResourceManager.GetString("RecibidoEfectivo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 158.
        /// </summary>
        internal static string RecibidoEfectivo_Y {
            get {
                return ResourceManager.GetString("RecibidoEfectivo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string RecibidoTesorero_X {
            get {
                return ResourceManager.GetString("RecibidoTesorero_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 188.
        /// </summary>
        internal static string RecibidoTesorero_Y {
            get {
                return ResourceManager.GetString("RecibidoTesorero_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string SaldoCaja_X {
            get {
                return ResourceManager.GetString("SaldoCaja_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 235.
        /// </summary>
        internal static string SaldoCaja_Y {
            get {
                return ResourceManager.GetString("SaldoCaja_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string SaldoCaja2_X {
            get {
                return ResourceManager.GetString("SaldoCaja2_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 575.
        /// </summary>
        internal static string SaldoCaja2_Y {
            get {
                return ResourceManager.GetString("SaldoCaja2_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string Sobrante_X {
            get {
                return ResourceManager.GetString("Sobrante_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 606.
        /// </summary>
        internal static string Sobrante_Y {
            get {
                return ResourceManager.GetString("Sobrante_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TB1_X {
            get {
                return ResourceManager.GetString("TB1_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 297.
        /// </summary>
        internal static string TB1_Y {
            get {
                return ResourceManager.GetString("TB1_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TB10_X {
            get {
                return ResourceManager.GetString("TB10_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 345.
        /// </summary>
        internal static string TB10_Y {
            get {
                return ResourceManager.GetString("TB10_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TB100_X {
            get {
                return ResourceManager.GetString("TB100_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 391.
        /// </summary>
        internal static string TB100_Y {
            get {
                return ResourceManager.GetString("TB100_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TB2_X {
            get {
                return ResourceManager.GetString("TB2_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 313.
        /// </summary>
        internal static string TB2_Y {
            get {
                return ResourceManager.GetString("TB2_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TB20_X {
            get {
                return ResourceManager.GetString("TB20_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 359.
        /// </summary>
        internal static string TB20_Y {
            get {
                return ResourceManager.GetString("TB20_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TB5_X {
            get {
                return ResourceManager.GetString("TB5_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 329.
        /// </summary>
        internal static string TB5_Y {
            get {
                return ResourceManager.GetString("TB5_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TB50_X {
            get {
                return ResourceManager.GetString("TB50_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 375.
        /// </summary>
        internal static string TB50_Y {
            get {
                return ResourceManager.GetString("TB50_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TB500_X {
            get {
                return ResourceManager.GetString("TB500_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 406.
        /// </summary>
        internal static string TB500_Y {
            get {
                return ResourceManager.GetString("TB500_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TM1_X {
            get {
                return ResourceManager.GetString("TM1_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 453.
        /// </summary>
        internal static string TM1_Y {
            get {
                return ResourceManager.GetString("TM1_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TM10_X {
            get {
                return ResourceManager.GetString("TM10_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string TM10_Y {
            get {
                return ResourceManager.GetString("TM10_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TM2_X {
            get {
                return ResourceManager.GetString("TM2_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 469.
        /// </summary>
        internal static string TM2_Y {
            get {
                return ResourceManager.GetString("TM2_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TM20_X {
            get {
                return ResourceManager.GetString("TM20_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 515.
        /// </summary>
        internal static string TM20_Y {
            get {
                return ResourceManager.GetString("TM20_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TM5_X {
            get {
                return ResourceManager.GetString("TM5_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 484.
        /// </summary>
        internal static string TM5_Y {
            get {
                return ResourceManager.GetString("TM5_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360.
        /// </summary>
        internal static string TM50_X {
            get {
                return ResourceManager.GetString("TM50_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 530.
        /// </summary>
        internal static string TM50_Y {
            get {
                return ResourceManager.GetString("TM50_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string TotalArqueo_X {
            get {
                return ResourceManager.GetString("TotalArqueo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 560.
        /// </summary>
        internal static string TotalArqueo_Y {
            get {
                return ResourceManager.GetString("TotalArqueo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string TotalBillete_X {
            get {
                return ResourceManager.GetString("TotalBillete_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 421.
        /// </summary>
        internal static string TotalBillete_Y {
            get {
                return ResourceManager.GetString("TotalBillete_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 487.
        /// </summary>
        internal static string TotalMoneda_X {
            get {
                return ResourceManager.GetString("TotalMoneda_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 545.
        /// </summary>
        internal static string TotalMoneda_Y {
            get {
                return ResourceManager.GetString("TotalMoneda_Y", resourceCulture);
            }
        }
    }
}
