//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcitas.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RQ3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RQ3() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appcitas.Recursos.RQ3", typeof(RQ3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 190.
        /// </summary>
        internal static string Fecha_X {
            get {
                return ResourceManager.GetString("Fecha_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 560.
        /// </summary>
        internal static string Fecha_Y {
            get {
                return ResourceManager.GetString("Fecha_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 220.
        /// </summary>
        internal static string Monto_X {
            get {
                return ResourceManager.GetString("Monto_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 417.
        /// </summary>
        internal static string Monto_Y {
            get {
                return ResourceManager.GetString("Monto_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 190.
        /// </summary>
        internal static string Nombre_cliente_X {
            get {
                return ResourceManager.GetString("Nombre_cliente_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 534.
        /// </summary>
        internal static string Nombre_cliente_Y {
            get {
                return ResourceManager.GetString("Nombre_cliente_Y", resourceCulture);
            }
        }
    }
}
