//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcitas.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class socioEconomico {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal socioEconomico() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appcitas.Recursos.socioEconomico", typeof(socioEconomico).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 285.
        /// </summary>
        internal static string ActAgropec_X {
            get {
                return ResourceManager.GetString("ActAgropec_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 422.
        /// </summary>
        internal static string ActAgropec_Y {
            get {
                return ResourceManager.GetString("ActAgropec_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string Alimentacion_X {
            get {
                return ResourceManager.GetString("Alimentacion_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 464.
        /// </summary>
        internal static string Alimentacion_Y {
            get {
                return ResourceManager.GetString("Alimentacion_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 370.
        /// </summary>
        internal static string CapacidadPago_X {
            get {
                return ResourceManager.GetString("CapacidadPago_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 570.
        /// </summary>
        internal static string CapacidadPago_Y {
            get {
                return ResourceManager.GetString("CapacidadPago_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 472.
        /// </summary>
        internal static string Celular_X {
            get {
                return ResourceManager.GetString("Celular_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 231.
        /// </summary>
        internal static string Celular_y {
            get {
                return ResourceManager.GetString("Celular_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 402.
        /// </summary>
        internal static string Dependientes_X {
            get {
                return ResourceManager.GetString("Dependientes_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 295.
        /// </summary>
        internal static string Dependientes_Y {
            get {
                return ResourceManager.GetString("Dependientes_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 170.
        /// </summary>
        internal static string Direccion_X {
            get {
                return ResourceManager.GetString("Direccion_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 231.
        /// </summary>
        internal static string Direccion_Y {
            get {
                return ResourceManager.GetString("Direccion_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 285.
        /// </summary>
        internal static string Negocio_X {
            get {
                return ResourceManager.GetString("Negocio_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 337.
        /// </summary>
        internal static string Negocio_Y {
            get {
                return ResourceManager.GetString("Negocio_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 250.
        /// </summary>
        internal static string Nombre_X {
            get {
                return ResourceManager.GetString("Nombre_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 210.
        /// </summary>
        internal static string Nombre_Y {
            get {
                return ResourceManager.GetString("Nombre_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 215.
        /// </summary>
        internal static string Observaciones_X {
            get {
                return ResourceManager.GetString("Observaciones_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 612.
        /// </summary>
        internal static string Observaciones_Y {
            get {
                return ResourceManager.GetString("Observaciones_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 285.
        /// </summary>
        internal static string Otros_X {
            get {
                return ResourceManager.GetString("Otros_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 464.
        /// </summary>
        internal static string Otros_Y {
            get {
                return ResourceManager.GetString("Otros_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string Prestamos_X {
            get {
                return ResourceManager.GetString("Prestamos_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 421.
        /// </summary>
        internal static string Prestamos_Y {
            get {
                return ResourceManager.GetString("Prestamos_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string Renta_X {
            get {
                return ResourceManager.GetString("Renta_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 337.
        /// </summary>
        internal static string Renta_Y {
            get {
                return ResourceManager.GetString("Renta_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 285.
        /// </summary>
        internal static string Salario_X {
            get {
                return ResourceManager.GetString("Salario_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 380.
        /// </summary>
        internal static string Salario_Y {
            get {
                return ResourceManager.GetString("Salario_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string ServPub_X {
            get {
                return ResourceManager.GetString("ServPub_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 380.
        /// </summary>
        internal static string ServPub_Y {
            get {
                return ResourceManager.GetString("ServPub_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string TotalEgresos_X {
            get {
                return ResourceManager.GetString("TotalEgresos_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 527.
        /// </summary>
        internal static string TotalEgresos_Y {
            get {
                return ResourceManager.GetString("TotalEgresos_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 285.
        /// </summary>
        internal static string TotalIngresos_X {
            get {
                return ResourceManager.GetString("TotalIngresos_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 527.
        /// </summary>
        internal static string TotalIngresos_Y {
            get {
                return ResourceManager.GetString("TotalIngresos_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string Transporte_X {
            get {
                return ResourceManager.GetString("Transporte_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 443.
        /// </summary>
        internal static string Transporte_Y {
            get {
                return ResourceManager.GetString("Transporte_Y", resourceCulture);
            }
        }
    }
}
