//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcitas.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class solicitudPrestamo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal solicitudPrestamo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appcitas.Recursos.solicitudPrestamo", typeof(solicitudPrestamo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 460.
        /// </summary>
        internal static string AvalCel_X {
            get {
                return ResourceManager.GetString("AvalCel_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 604.
        /// </summary>
        internal static string AvalCel_Y {
            get {
                return ResourceManager.GetString("AvalCel_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 165.
        /// </summary>
        internal static string AvalNomb_X {
            get {
                return ResourceManager.GetString("AvalNomb_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 604.
        /// </summary>
        internal static string AvalNomb_Y {
            get {
                return ResourceManager.GetString("AvalNomb_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 460.
        /// </summary>
        internal static string Cel_Aval2_X {
            get {
                return ResourceManager.GetString("Cel_Aval2_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 627.
        /// </summary>
        internal static string Cel_Aval2_Y {
            get {
                return ResourceManager.GetString("Cel_Aval2_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 480.
        /// </summary>
        internal static string Celular_X {
            get {
                return ResourceManager.GetString("Celular_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 290.
        /// </summary>
        internal static string Celular_Y {
            get {
                return ResourceManager.GetString("Celular_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string CreditoN_X {
            get {
                return ResourceManager.GetString("CreditoN_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 447.
        /// </summary>
        internal static string CreditoN_Y {
            get {
                return ResourceManager.GetString("CreditoN_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 205.
        /// </summary>
        internal static string Cuota_X {
            get {
                return ResourceManager.GetString("Cuota_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 425.
        /// </summary>
        internal static string Cuota_Y {
            get {
                return ResourceManager.GetString("Cuota_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 229.
        /// </summary>
        internal static string DirTrabajo_X {
            get {
                return ResourceManager.GetString("DirTrabajo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 267.
        /// </summary>
        internal static string DirTrabajo_Y {
            get {
                return ResourceManager.GetString("DirTrabajo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        internal static string Domicilio_X {
            get {
                return ResourceManager.GetString("Domicilio_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 245.
        /// </summary>
        internal static string Domicilio_Y {
            get {
                return ResourceManager.GetString("Domicilio_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 480.
        /// </summary>
        internal static string EstadoCivil_X {
            get {
                return ResourceManager.GetString("EstadoCivil_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 222.
        /// </summary>
        internal static string EstadoCivil_Y {
            get {
                return ResourceManager.GetString("EstadoCivil_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 518.
        /// </summary>
        internal static string FecDesembolso_X {
            get {
                return ResourceManager.GetString("FecDesembolso_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 424.
        /// </summary>
        internal static string FecDesembolso_Y {
            get {
                return ResourceManager.GetString("FecDesembolso_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 420.
        /// </summary>
        internal static string Fecha_X {
            get {
                return ResourceManager.GetString("Fecha_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 188.
        /// </summary>
        internal static string Fecha_Y {
            get {
                return ResourceManager.GetString("Fecha_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string FormaPago_X {
            get {
                return ResourceManager.GetString("FormaPago_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 401.
        /// </summary>
        internal static string FormaPago_Y {
            get {
                return ResourceManager.GetString("FormaPago_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        internal static string Identidad_X {
            get {
                return ResourceManager.GetString("Identidad_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 222.
        /// </summary>
        internal static string Identidad_Y {
            get {
                return ResourceManager.GetString("Identidad_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 150.
        /// </summary>
        internal static string Lugar_X {
            get {
                return ResourceManager.GetString("Lugar_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 188.
        /// </summary>
        internal static string Lugar_Y {
            get {
                return ResourceManager.GetString("Lugar_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 210.
        /// </summary>
        internal static string MontoAprob_X {
            get {
                return ResourceManager.GetString("MontoAprob_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 447.
        /// </summary>
        internal static string MontoAprob_Y {
            get {
                return ResourceManager.GetString("MontoAprob_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        internal static string MontoSol_X {
            get {
                return ResourceManager.GetString("MontoSol_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 357.
        /// </summary>
        internal static string MontoSol_Y {
            get {
                return ResourceManager.GetString("MontoSol_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 165.
        /// </summary>
        internal static string Nom_Aval2_X {
            get {
                return ResourceManager.GetString("Nom_Aval2_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 627.
        /// </summary>
        internal static string Nom_Aval2_Y {
            get {
                return ResourceManager.GetString("Nom_Aval2_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 228.
        /// </summary>
        internal static string ObjetivoPres_X {
            get {
                return ResourceManager.GetString("ObjetivoPres_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 469.
        /// </summary>
        internal static string ObjetivoPres_Y {
            get {
                return ResourceManager.GetString("ObjetivoPres_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 170.
        /// </summary>
        internal static string Observacion_X {
            get {
                return ResourceManager.GetString("Observacion_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 530.
        /// </summary>
        internal static string Observacion_Y {
            get {
                return ResourceManager.GetString("Observacion_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string Plazo_X {
            get {
                return ResourceManager.GetString("Plazo_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 378.
        /// </summary>
        internal static string Plazo_Y {
            get {
                return ResourceManager.GetString("Plazo_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 220.
        /// </summary>
        internal static string Profesion_X {
            get {
                return ResourceManager.GetString("Profesion_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 290.
        /// </summary>
        internal static string Profesion_Y {
            get {
                return ResourceManager.GetString("Profesion_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        internal static string TasaInt_X {
            get {
                return ResourceManager.GetString("TasaInt_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 378.
        /// </summary>
        internal static string TasaInt_Y {
            get {
                return ResourceManager.GetString("TasaInt_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 480.
        /// </summary>
        internal static string Tel_X {
            get {
                return ResourceManager.GetString("Tel_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 267.
        /// </summary>
        internal static string Tel_Y {
            get {
                return ResourceManager.GetString("Tel_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        internal static string TipoGaran_X {
            get {
                return ResourceManager.GetString("TipoGaran_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 401.
        /// </summary>
        internal static string TipoGaran_Y {
            get {
                return ResourceManager.GetString("TipoGaran_Y", resourceCulture);
            }
        }
    }
}
